project:
  type: book
  output-dir: docs

book:
  title: "tidymodels Gallery"
  author: "Emil hvitfeldt"
  date: "8/10/2021"
  chapters:
    - index.qmd
    - chapter/visualize-decision-trees.qmd
    - chapter/dealing-with-datetime.qmd

bibliography: references.bib

format:
  html:
    theme: Cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png

